<?php

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function asc_quicksites_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#asc_quicksites":
      $output = '<p>'.  t("Helper module for QuickSites") .'</p>';
      break;
  }
  return $output;
} // function asc_quicksites_help

/**
 * Implementation of hook_block().
 * @param string $op one of "list", "view", "save" and "configure"
 * @param integer $delta code to identify the block
 * @param array $edit only for "save" operation
 */
function asc_quicksites_block($op = 'list', $delta = 0, $edit = array()) {

  // set up an empty array which will contain the block contents
    $block = array();

    if ($op == "list") {
      // Generate listing of blocks from this module, for the admin/block page
      $block[0]["info"] = t('People Index');
    }
    elseif ($op == 'view') {

      // Generate our block content

      // content variable that will be returned for display
      $block_content = '';

      $sql = "
        SELECT SUBSTR(node.title, 1, 1) AS title_truncated, COUNT(node.nid) AS num_records
        FROM node node
        WHERE (node.status <> 0) AND (node.type in ('qs_people'))
        GROUP BY title_truncated
        ORDER BY title_truncated ASC
      ";

      $result = db_query($sql);
      
      $current_letter = trim(arg(1));

      $block_content .= '<div id="directory_glossary">';
      
      // Initialize the base_url variable
      global $base_url;
      
      if ($current_letter == '') {
        $block_content .= '<ul><li><a class="selected" href="' . $base_url . '/directory/" title="View all people.">All</a></li>';
      }
      else {
        $block_content .= '<ul><li><a href="' . $base_url . '/directory/" title="View all people.">All</a></li>';
      }

      while ($row = db_fetch_object($result)) {
        if ($current_letter == $row->title_truncated) {
          $block_content .= '<li><a class="selected" href="' . $base_url . '/' . 'directory/' . $row->title_truncated . '" title="View people with last names that begin with &quot;' . $row->title_truncated . '&quot;">' . strtoupper($row->title_truncated) . '</a></li>';
        }
        else {
          $block_content .= '<li><a href="' . $base_url . '/' . 'directory/' . $row->title_truncated . '" title="View people with last names that begin with &quot;' . $row->title_truncated . '&quot;">' . strtoupper($row->title_truncated) . '</a></li>';
        }
      }
      $block_content .= '</ul>';
      $block_content .= '</div>';
      $block_content .= '<br class="clear"/>';

      // Fill in the subject of our block which is the same whether or not
      // the block has any real content
      $block['subject'] = 'People Index';

      // set up the block
      $block['content'] = $block_content;
    }

    return $block;

} // function asc_quicksites_block
